# Generated by Django 3.0.5 on 2020-09-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200720_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtitle',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
